### PR TITLE
Remove Cython pin

### LINKED ISSUE #2: Python 3.5?
Does this or is this suppose to support Python 3.5?

### LINKED ISSUE #7: Cython pin
Is it possible to remove the Cython version pin, or replace it with >=? This causes problems with other packages that require newer versions of Cython.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #7. 
Fixes #2.

I don't know why the pin was there, so we should make sure everything still works after this. If the build passes, maybe we should run the full test suite if that's possible.

### CODE REVIEW

**Comment by asmeurer** [comment]
I think it must have come from the original setup.py. It now says Cython>=0.19 https://github.com/uweschmitt/autowrap/blob/644a4cc77525489839d6d3bbd4574e8119deafe4/setup.py#L45

**Comment by asmeurer** [comment]
c.f. https://github.com/uweschmitt/autowrap/pull/53. I'll change the pin to >= to match the setup.py

**Comment by asmeurer** [comment]
CC @aseyboldt

**Comment by asmeurer** [comment]
CC @conda-forge/core can someone merge this?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
